/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: OneSteven (https://sketchfab.com/Steven007)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/apple-iphone-11-pro-e88c8489a48b494bb4db178c2907f737
title: Apple iPhone 11 Pro
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 4]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[-0.04, 0.81, 0.05]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object_A_0.geometry} material={materials.material} castShadow />
            </group>
            <group position={[-0.05, 0, 0.05]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object001_alu_0.geometry} material={materials.material_1} castShadow />
            </group>
            <group position={[11.65, 69.22, -1.8]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object002_fash_0.geometry} material={materials.fash} castShadow />
            </group>
            <group position={[4.22, 59.37, 0.51]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object003_gryl_0.geometry} material={materials.gryl} castShadow />
            </group>
            <group position={[17.27, 61.04, 0.28]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object004_lense_0.geometry} material={materials.lense} castShadow />
            </group>
            <group position={[18.84, 58.09, -3.35]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object005_dchr_0.geometry} material={materials.dchr} castShadow />
            </group>
            <group position={[-0.05, 0, 3.49]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object006_bezel_0.geometry} material={materials.bezel} castShadow />
            </group>
            <group position={[0, 36.09, 0.1]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object007_but_0.geometry} material={materials.material_7} castShadow />
            </group>
            <group position={[-0.05, 0, 0.05]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object008_ant_0.geometry} material={materials.material_8} castShadow />
            </group>
            <group position={[18.84, 58.08, -3.11]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object009_chr_0.geometry} material={materials.material_9} castShadow />
            </group>
            <group position={[-0.05, 0, 3.86]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object010_scr_0.geometry} material={materials.material_10} castShadow />
            </group>
            <group position={[18.84, 58.08, -3.65]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object011_glsl_0.geometry} material={materials.glsl} castShadow />
            </group>
            <group position={[-0.05, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object012_glass_0.geometry} material={materials.glass} castShadow />
            </group>
            <group position={[18.83, 59.04, 0.03]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object013_misc1_0.geometry} material={materials.misc1} castShadow />
            </group>
            <group position={[0.5, 6.14, -3.08]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object014_logo_0.geometry} material={materials.logo} castShadow />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
